name: Zig embedded

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-linux-gnu
          - target: aarch64-linux
          - target: riscv64-linux-musl
          - target: powerpc64-linux
          - target: aarch64-windows
          - target: aarch64-linux-android
            android_api: "29"
          - target: arm-linux-androideabi
            android_api: "29"
          - target: x86_64-linux-android
            android_api: "29"
          - target: x86-linux-android
            android_api: "29"
          - target: riscv64-linux-android
            android_api: "35"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Setup Android NDK
        if: contains(matrix.target, 'android')
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29
          local-cache: true
      
      - name: Build Summary ${{ matrix.target }}
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          ARGS="-Dtarget=${{ matrix.target }}"
          if [ -n "${{ matrix.android_api }}" ]; then
            ARGS="$ARGS.${{ matrix.android_api }}"
          fi
          zig build --summary all -freference-trace $ARGS
      - name: Build Summary - Zig Package ${{ matrix.target }}
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          ARGS="-Dtarget=${{ matrix.target }}"
          zig build --build-file $PWD/test_zigpkg/build.zig --summary all -freference-trace $ARGS
